version: '3.3'

services:

  video:
    container_name: video
    build:
      context: ./services/video
      dockerfile: Dockerfile-dev
    volumes:
      - './services/video:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - FLASK_DEBUG=1
    devices: 
      - /dev/video0:/dev/video0

    depends_on:
      - face
    links:
      - face

  face:
    container_name: face
    build:
      context: ./services/face
      dockerfile: Dockerfile-dev
    volumes:
      - './services/face:/usr/src/app'
    ports:
      - 5002:5000
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - FLASK_DEBUG=1